<a href="https://colab.research.google.com/github/laxmijin11-cyber/MACHINE-LEARNING/blob/main/Naive_Bayes/2_naive_bayes_dataset_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [86]:
# NAIVE BAYE'S ALGORITHM ON TIPS DATASET
import seaborn as sns
tips=sns.load_dataset('tips')

In [74]:
tips['is_smoker']=(tips['smoker']=='Yes').astype('int')
# 0 for no and 1 for yes

In [75]:
tips

     total_bill   tip     sex smoker   day    time  size  is_smoker
0         16.99  1.01  Female     No   Sun  Dinner     2          0
1         10.34  1.66    Male     No   Sun  Dinner     3          0
2         21.01  3.50    Male     No   Sun  Dinner     3          0
3         23.68  3.31    Male     No   Sun  Dinner     2          0
4         24.59  3.61  Female     No   Sun  Dinner     4          0
..          ...   ...     ...    ...   ...     ...   ...        ...
239       29.03  5.92    Male     No   Sat  Dinner     3          0
240       27.18  2.00  Female    Yes   Sat  Dinner     2          1
241       22.67  2.00    Male    Yes   Sat  Dinner     2          1
242       17.82  1.75    Male     No   Sat  Dinner     2          0
243       18.78  3.00  Female     No  Thur  Dinner     2          0

[244 rows x 8 columns]

# 🔧 LabelEncoder vs OneHotEncoder – What They Do

---

## ✅ Short Answer

Both convert **text categories into numbers** so machine learning models can understand them.

| Encoder | Output | Best For |
|---------|--------|----------|
| **LabelEncoder** | Single column of numbers (0,1,2,3...) | Ordinal data (Small < Medium < Large) |
| **OneHotEncoder** | Multiple columns (1 or 0 for each category) | Nominal data (Red, Blue, Green - no order) |

---

## 📊 Example: `day` column (Mon, Tue, Wed)

### Original Data
```
day
Mon
Tue
Wed
Mon
```

### LabelEncoder Output (Single Column)
```
day_encoded
0
1
2
0
```
⚠️ **Problem:** Model might think Tue (1) > Mon (0) or Wed (2) > Tue (1) – which is meaningless.

### OneHotEncoder Output (Three Columns)
```
day_Mon  day_Tue  day_Wed
1        0        0
0        1        0
0        0        1
1        0        0
```
✅ **No order implied** – each category is independent.

---

Combines two steps into ONE:

fit() – Learns the categories (e.g., Male → 0, Female → 1)

transform() – Converts the data using what it learned

# 🎯 Nominal vs Ordinal

---

## ✅ One Line

- **Nominal** = Names only (no order)
- **Ordinal** = Order matters

---

## 📊 Examples

| Data | Type | Why |
|------|------|-----|
| **Red, Blue, Green** | Nominal | No rank (Red isn't "greater" than Blue) |
| **Male, Female** | Nominal | No order |
| **Small, Medium, Large** | Ordinal | Size order matters |
| **1st, 2nd, 3rd** | Ordinal | Position order matters |
| **Poor, Average, Good** | Ordinal | Quality order matters |
| **Sun, Mon, Tue** | Nominal | Days have no inherent rank |

---

## 🔍 Your `tips` Data

| Column | Type | Why |
|--------|------|-----|
| `sex` (Male/Female) | **Nominal** | No order |
| `day` (Sun, Mon, Tue...) | **Nominal** | Sunday isn't "greater" than Monday |
| `time` (Lunch/Dinner) | **Nominal** | No order |

**None are ordinal. Use OneHotEncoder.**

---

## 💡 Memory Trick

```text
Nominal = Name (just a label):OneHotEncoder()
Ordinal = Order (has a sequence):LabelEncoder()
```

**If you can't say "A is greater than B" → it's Nominal.** 🚀

In [76]:
'''
from sklearn.preprocessing import LabelEncoder
# Converts text categories into numbers (0, 1, 2, ...) in one step.
tips['sex_encoded']=LabelEncoder().fit_transform(tips['sex'])
tips['time_encoded']=LabelEncoder().fit_transform(tips['time'])
tips['day_encoded']=LabelEncoder().fit_transform(tips['day'])
'''
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder(sparse_output=False)
encoded_df=pd.DataFrame(encoder.fit_transform(tips[['sex','day','time']]),
                        columns=encoder.get_feature_names_out(['sex','day','time']))

fit_transform() Needs 2D Array

Why `tips[['sex','day','time']]` Has Double Brackets

---

## Short Answer

**First bracket = DataFrame indexing. Second bracket = list of column names.**

---

## Single vs Double Bracket

| Code | Result | Type |
|------|--------|------|
| `tips['sex']` | One column | Series (1D) |
| `tips[['sex']]` | One column | DataFrame (2D) |
| `tips[['sex','day']]` | Two columns | DataFrame (2D) |

---

##  Why It Matters

`fit_transform()` needs **2D data** (DataFrame), not 1D (Series).

```python
# Wrong - 1D Series
encoder.fit_transform(tips['sex'])

# Correct - 2D DataFrame
encoder.fit_transform(tips[['sex']])
```

---

## One Line Memory Trick

**Single bracket = Series (1D). Double bracket = DataFrame (2D).**

In [77]:
encoded_df

,sex_Female,sex_Male,day_Fri,day_Sat,day_Sun,day_Thur,time_Dinner,time_Lunch
0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
3,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
239,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
240,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
241,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
242,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
243,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [78]:
tips

     total_bill   tip     sex smoker   day    time  size  is_smoker
0         16.99  1.01  Female     No   Sun  Dinner     2          0
1         10.34  1.66    Male     No   Sun  Dinner     3          0
2         21.01  3.50    Male     No   Sun  Dinner     3          0
3         23.68  3.31    Male     No   Sun  Dinner     2          0
4         24.59  3.61  Female     No   Sun  Dinner     4          0
..          ...   ...     ...    ...   ...     ...   ...        ...
239       29.03  5.92    Male     No   Sat  Dinner     3          0
240       27.18  2.00  Female    Yes   Sat  Dinner     2          1
241       22.67  2.00    Male    Yes   Sat  Dinner     2          1
242       17.82  1.75    Male     No   Sat  Dinner     2          0
243       18.78  3.00  Female     No  Thur  Dinner     2          0

[244 rows x 8 columns]

In [79]:
# x=tips[['total_bill','tip','size','sex_encoded','time_encoded','day_encoded']]
# y=tips['is_smoker']

x=pd.concat([tips[['total_bill','tip','size']],encoded_df],axis=1)
y=tips['is_smoker']
x

,total_bill,tip,size,sex_Female,sex_Male,day_Fri,day_Sat,day_Sun,day_Thur,time_Dinner,time_Lunch
0,16.99,1.01,2,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,10.34,1.66,3,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
2,21.01,3.50,3,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
3,23.68,3.31,2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
4,24.59,3.61,4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,3,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
240,27.18,2.00,2,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
241,22.67,2.00,2,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
242,17.82,1.75,2,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
243,18.78,3.00,2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In x, They are alredy tips[[ ]] and encoded_df 2d then why outer [ ] when already both are 2d...?

# 🔍 Why Outer `[ ]` in `pd.concat([...])`

You're right that both `tips[['total_bill','tip','size']]` and `encoded_df` are **2D DataFrames**.

The outer `[ ]` is **NOT for them** – it's for **`pd.concat()` function**.

---

##  Correct Understanding

```python
pd.concat([df1, df2], axis=1)
           ↑      ↑
           │      └── Second DataFrame
           └── First DataFrame
```

The **outer square brackets** create a **Python list** containing the DataFrames.

---

## 📊 What Happens Inside

```python
# What you write
pd.concat([df1, df2], axis=1)

# What Python sees
pd.concat( [df1, df2] , axis=1)
           ↑         ↑
           └─ list ──┘
```

---

## Without Outer `[ ]` (Wrong)

```python
pd.concat(df1, df2, axis=1)  # ❌ Error - df2 becomes 'axis' parameter
```

Python thinks `df2` is the `axis` parameter, not a second DataFrame.

---

## One Line Memory Trick

**`pd.concat([df1, df2, df3])` – Put ALL DataFrames inside a list `[ ]`.** 🚀

In [80]:
x

,total_bill,tip,size,sex_Female,sex_Male,day_Fri,day_Sat,day_Sun,day_Thur,time_Dinner,time_Lunch
0,16.99,1.01,2,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,10.34,1.66,3,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
2,21.01,3.50,3,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
3,23.68,3.31,2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
4,24.59,3.61,4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,3,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
240,27.18,2.00,2,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
241,22.67,2.00,2,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
242,17.82,1.75,2,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
243,18.78,3.00,2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [81]:
y

0      0
1      0
2      0
3      0
4      0
      ..
239    0
240    1
241    1
242    0
243    0
Name: is_smoker, Length: 244, dtype: int64

In [82]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(x_train,y_train)
y_pred=gnb.predict(x_test)

In [83]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [84]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[30  9]
 [18 17]]
0.6351351351351351
              precision    recall  f1-score   support

           0       0.62      0.77      0.69        39
           1       0.65      0.49      0.56        35

    accuracy                           0.64        74
   macro avg       0.64      0.63      0.62        74
weighted avg       0.64      0.64      0.63        74

In [85]:
# This shows Naive Baye's Classification Algorithm!